### ISSUE TITLE
$panels problems

### ISSUE THREAD

**Issue by dandancheeseandham** [dandancheeseandham/cheesecore#19]
Currently in config.scad there is the lines from line 37
```
function side_panel_thickness()     = 2 ; // $panels[1]
function panel_radius()             = 5; // $panels[2]
```

When a make_railcore300zlcompatible.scad is run (this is the one I've tested with, it does the same with others), there is output from core.scad these lines
```
  echo ("$panels[1]: ",$panels[1]);
  echo ("side_panel_thickness(): ",side_panel_thickness() );
  echo ("$panels: ",$panels);
```
to the tune of 
```
ECHO: "$panels[1]: ", 6.35
ECHO: "side_panel_thickness(): ", 2
ECHO: "$panels: ", ["PANELS", 6.35, 5, 6.35, 0, 50]
```

if line 37 in config.scad is changed to
```
function side_panel_thickness()     = $panels[1] ;
```
the output breaks, no printer is rendered and the first error is
```
WARNING: Ignoring unknown variable '$panels', in file config.scad, line 37.
```
Except it is defined and is seen in the output echoed.

It seems "function panel_radius()" can be changed to "$panels[2]" though!

**Comment by lostapathy** [comment]
I created [this branch](https://github.com/lostapathy/cheesecore/tree/panel_issue) to replicate the issue.  By the time I got to this the line numbers had already changed.  Going forward, just for the sake of clarity and expediency, it's probably worth having the reporter create and publish this type of branch that shows issues like this and then referencing it in the issue.

**Comment by lostapathy** [comment]
The error actually comes from [this block](https://github.com/lostapathy/cheesecore/blob/panel_issue/config.scad#L97).  Since that code is defined right in config.scad (and not in a module/function), it gets evaluated when the file is processed, and outside the scope of any printer definitions that would define the special $panels variable.

I would fix this by basically removing all of those definitions, and making a function to the effect of that calculated the halo size at runtime based on the machine definition, and not trying to build that up in the config.  I can help you work through that, but I need to get back up to speed on other code changes first to really understand what's going on.

**Comment by lostapathy** [comment]
As far as how to troubleshoot this type of error - I commented out the line generating the warning.  That causes an error to be thrown by the caller of the problematic function ("Ignoring unknown function").  You can then look at the caller(s) that are throwing errors and in this case it was pretty obvious why $panels wasn't defined where you expected it to be.
